### ISSUE TITLE
Github Warning about call to init_sims

### ISSUE THREAD

**Issue by Wafik20** [lampealex888/capstone-foodsocial#1]
GitHub is issuing the following warning in your notebook. Should we just ignore this?

<ipython-input-215-512da4c72c44>:31: DeprecationWarning: Call to deprecated `init_sims` (Gensim 4.0.0 implemented internal optimizations that make calls to init_sims() unnecessary. init_sims() is now obsoleted and will be completely removed in future versions. See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4).
  model.init_sims(replace=True)
WARNING:gensim.models.keyedvectors:destructive init_sims(replace=True) deprecated & no longer required for space-efficiency

**Comment by lampealex888** [comment]
Yes, we should remove it. I'll remove it on my next commit.
