### ISSUE TITLE
I don't think we need a php plugin, right?

### ISSUE THREAD

**Issue by Wafik20** [lampealex888/capstone-foodsocial#2]
Creating php plugin is unnecessary for now. The Flask server will have to run on a different port than our WordPress app. We will contact with the machine learning model through the API by simply making http requests to the endpoints you created. The http requests will be done either on the backend of the wordpress app (if we decide so, we will have to create a php plugin) or on the frontend (in that case a php plugin is not needed)

**Comment by lampealex888** [comment]
Jon talked about the requests being made on the backend because it's a security vulnerability if they can call the API from the front end. Regardless, we should focus on the MVP. So we can skip the plugin for now, unless Shreya has already created it.

**Comment by Wafik20** [comment]
Another problem:

The way I imagine the recipe recommender to work is that it should provide a link to an existing recipe on the website. And the model seems to only provide the name of the recipe not its link or its id in the actual wordpress database.

**Comment by lampealex888** [comment]
The recipe recommender will give the user the recipe link. It won't give the user the recipe ID by design, but could if the code was changed. A WP plugin was necessary because JS cannot call HTTP servers. So I had to make the call using PHP.

**Comment by Wafik20** [comment]
JavaScript can definitely do HTTPS requests! This happens in almost every web app in existence. For example, you login on Facebook, you send a POST request through the React fronted to the backend server on the port where API is listening. The backend responds with a JSON response to the frontend on the port where the front end is listening. In our case we can do an HTTP get request to your Flask endpoint by simply using Ajax. And I think we can definitely tackle the security problem by specifying the IP addresses that can make a request to backend (shouldn't be too difficult ).


The Ajax request should look something like this:

``<script>
    $(document).ready(function() {
        $('#getRecipesBtn').click(function() {
            var ingredients = $('#ingredientsInput').val();
            var apiUrl = 'http://127.0.0.1:5000/recipe'; // This basically assumes that the backend is listening on port 5000 on localhost
            $.ajax({
                url: apiUrl,
                type: 'GET',
                data: { 'ingredients': ingredients },
                success: function(response) {
                    $('#recipes').empty(); // Clear previous results
                    $.each(response, function(index, recipe) {
                        var recipeElement = `
                            <div>
                                <h3>${recipe.recipe}</h3>
                                <p>Score: ${recipe.score}</p>
                                <p>Ingredients: ${recipe.ingredients}</p>
                                <a href="${recipe.url}">Recipe Link</a>
                            </div>
                        `;
                        $('#recipes').append(recipeElement);
                    });
                }
            });
        });
    });
</script>
``

**Comment by lampealex888** [comment]
Sorry I should have been more specific. I meant that I can't make calls to unsafe URLs that don't SSL encryption (HTTP) with JS without changing the protections of the Wordpress server, which I imagine Jon wouldn't want us to do. This is because HTTPS won't makes calls to HTTP because it defeats the SSL security aspect of HTTPS. I tried to get SSL encryption on the Flask server so that we could make an HTTPS request instead. But you need a domain name and I'm not paying for a domain.

**Comment by lampealex888** [comment]
Also making an Ajax call through the client is bad because it exposes the API URL, which is not what we want. So there's that too. You can try implementing it your way, but I already got the plugin working.

**Comment by Wafik20** [comment]
Ohhh I see now. No, you definitely have a point! I kinda agree with you now. I also agree that our top priority should be to get features up and running. Great work btw! You definitely rocked this sprint!
